baseURL = "https://lifailon.github.io"
languageCode = "en-us"
title = "ruDocs"

# git clone https://github.com/JingWangTW/dark-theme-editor.git themes/dark-theme-editor
theme = "dark-theme-editor"

[params]

[params.header]
# Заголовок сайта (указывается в шапке, теме и наименование вкладки главной страницы)
title = "Lifailon.GitHub.io"
# Описание на главное странице
subtitle = "Веб-версия заметок по PowerShell, командам Linux, инструментам DevOps, синтаксису Go и Node.js на русском языке."

# Логотип
[params.header.logo]
imgUrl = ""
logoLink = ""

# Фавикон
[params.site]
faviconUrl = ""

# Описание параметров нижнего колонтитула
[params.footer]
copyrightStr = "GitHub"
counter = false # Оторажать количество странц (index файлов)
language = false # Отображать текущий язык (en)
hugoVersion = true # Отображать текущую версию сборки hugo
theme = true # Отображать название темы (при нажатии переадресует на репозиторий GitHub)
modifiedTime = true # Отображать последнюю дату внесенных изменений 
dateFormat = "Jan 02 2006" # Формат отображаемой даты
gitHash = false

# Ссылки на социальные сети (отображается соответствующая иконка в левом углу, если параметр не пустой)
[params.footer.socialLink]
github = "https://github.com/Lifailon"
email = ""
telegram = ""
youtube = ""
instagram = ""
facebook = ""
twitter = ""
linkedin = ""
medium = ""
vimeo = ""

# Наименование автора, отображается в левом нижнем углу
[params.globalFrontmatter]
author = "Lifailon"

# Описание главное страницы
[params.homePage]
siteLongDescriptionTitle = "ruDocs"
siteLongDescription = "Структура языка, синтаксис командлетов и модулей, работа с системными и внешними утилитами, платформой .NET, различными сервисами через REST API, а так же системами AD, Exchange, Hyper-V, VMWare, базами данных и т.д."
showRecentPostsBlock = false # Отображать последние добавленные посты на главной страницы
numOfRecentPosts = 5 # Количество отображамых постов
recentPostShowUrl = false # Отображать путь рядом с постами

# Настройки страницы постов (Markdown)
[params.page]
includeToc = true # Отображать меню для навигации по странице (создается автоматически из заголовков)
showAuthor = true # Отображать автора страницы
showDate = true # Отображать дату публикации
dateFormat = "Jan 02 2006" # Формат отображаемой даты
showTimeToRead = true # Отображать время на чтение статьи в минутах
showBreadcrumb = true # Отображать путь к странице в меню сверху (Home / Databases / InfluxDB)
codeBlockCopible = true # Добавить кнопку копирования для блока кода
