site_name: PowerShell Commands
site_url: https://lifailon.github.io
repo_url: https://github.com/Lifailon/PS-Commands
copyright: Copyright © 2023-2024 Alex Kup (Lifailon)

docs_dir: content

nav:
  - Home: _index.md
  - PowerShell: PowerShell/index.md
  - Linux: Linux/index.md
  - DevOps: DevOps/index.md
  - DevOps: Compose/index.md
  - GoLang: GoLang/index.md
  - Node.js: Node-js/index.md

  # alternate:
  #   - name: Русский
  #     link: .
  #     lang: ru
  #   - name: English
  #     link: ./en/
  #     lang: en

# theme: readthedocs
# theme: bootstrap4

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Lifailon/PS-Commands
      name: PS-Commands on Github

theme:
  name: material

  logo: assets/logo.png
  favicon: assets/logo.png

  font:
    text: Inter
    code: Inter

  features:
    - content.code.copy

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

markdown_extensions:
  - markdown.extensions.nl2br

plugins:
  - search

extra_css:
  # https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/obsidian.min.css
  - assets/highlight/obsidian.min.css
  - assets/custom/headers.css

extra_javascript:
  # https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/highlight.min.js
  # https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/languages/powershell.min.js
  - assets/highlight/highlight.min.js
  - assets/highlight/powershell.min.js
  - assets/highlight/init.js